version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:8.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
  kibana:
    image: kibana:8.8.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  